src/renderer/components/shared/KeyspacesHandler.vue

When user clicked on keyspaces button, a click event was triggered which closed the list of keyspaces.
commented out for now.

comment out watcher for showKeyspaceList

---

src/renderer/components/Visualiser/VisualiserUtils.js
test/unit/components/Visualiser/VisualiserUtils.test.js

To put offset before limit when a query contains only a limit entered by the user.
Edit limit regex to extract query without limit
Create a condition where a query contains a limit but no offset so an offset can be placed between the query and limit.

Limit query bug

---

src/renderer/components/Visualiser/VisualiserGraphBuilder.js
test/helpers/MockConcepts.js
test/unit/components/Visualiser/VisualiserGraphBuilder.test.js
test/unit/components/Visualiser/VisualiserUtils.test.js

closes: #79
Check if the response from Grakn is a conjunction by checking the query pattern (which will be empty).
Then go inside the answers of the explanation and attach the explanation (pertaining to the individual conjunction statement) to the concepts.

Conjunction explanation bug

---

src/renderer/components/Visualiser/VisualiserUtils.js
test/unit/components/Visualiser/VisualiserUtils.test.js

Fixes a bug, when an explanation comprises of a relation and its attribute, construct valid queries.
When explanation answers contains a relation, create a query rather than an attribute query. 
This way the order of concept wont matter and a query will be constructed more robustly.

Explanation bug - When explanation answer contains a relationship and its attribute

---

.circleci/config.yml

Revert `deploy_github` in `release-github-draft` and use `ghr` directly.
We can't use the `deploy_github` rule for uploading distributions on the Workbase repo due to https://github.com/graknlabs/workbase/issues/17
Revert `deploy_github` in `release-github-draft` and use `ghr` directly.

Revert deploy_github which can't be used due to issue #17

---

src/renderer/components/Login/LoginPage.vue

In grakn v1.5 the method grakn.session() throws error when grakn is not running as apposed to session.transaction().
If grakn was not running "const session = await grakn.session('grakn');" throws an error which was not caught.
Remove creation of tranaction from login, and catch error on the grakn.session() function instead.

Catch error thrown by grakn.session()

---

.circleci/config.yml
.circleci/windows/assemble.py

Fix a Windows-specific build errors on the `assemble-windows` CI job (eg., [this one](https://circleci.com/gh/graknlabs/workbase/803)) which is caused by missing Python dependencies. 
Closes https://github.com/graknlabs/workbase/issues/88
Install `wheel` on Windows:
```
pip install wheel
```
which is needed by the CI job

Fix build-tools error by installing python dependencies

---

.circleci/windows/assemble.py

Fixes copying of built Workbase for Windows from GCP to CircleCI
Adds `-T` option to `scp` which suppresses strict filename check when copying from remote to host.
[ref](https://unix.stackexchange.com/questions/499958/why-does-scps-strict-filename-checking-reject-quoted-last-component-but-not-oth)
Given that our path contains spaces, we'd be better turning the check off rather than figuring out correct sequence for escaping all spaces. Also, we _do_ trust our own GCP host.

Fix Workbase Windows CI

---

WORKSPACE

Fix breaking change caused by the introduction of `benchmark` repository as a Bazel git_repository dependency.
One liner to include `graknlabs_benchmark()` dependency that allows the building of distribution `tar.gz` in CircleCI.

Add benchmark as transitive dependency

---

BUILD.bazel
config/brew/BUILD
config/brew/grakn-workbase.rb

Deploy Workbase to Caskroom (our custom tap)
- Bump `@graknlabs_build_tools` version which includes changes in graknlabs/bazel-distribution#88
- Add Caskroom formula for Workbase
- Add `bazel` target to deploy to tap

deploy_brew Caskroom deployment for Workbase

---

package.json
version.js

Fixes #109 (it will need re-releasing though)
Workbase version should be read from `VERSION`, just like in other repos
`prebuild` stage invokes `version.js`
`version.js` puts contents of `VERSION` into `package.json`'s `version` field
`postbuild` stage returns the file to its initial state
`package.json` now contains placeholder instead of proper version so we don't forget that there's a script that generates it.

Implement versioning as prebuild step

---

.circleci/config.yml

The Apple Certificate signing in the `assemble-mac` CI job is broken. This PR fixes that
Define the environment variables containing the certificate appropriately

assemble-mac - Fix Apple certificate signing issue

---

src/renderer/components/Visualiser/VisualiserUtils.js

To fix the bug of double clicking on nodes to retrieve neighbours
closes: #135 
Remove quotes around the ID inside the query used to retrieve neighbours.

Fix retrieving of neighbours of a node

---

src/renderer/components/Visualiser/ContextMenu.vue
src/renderer/components/Visualiser/VisualiserGraphBuilder.js
test/unit/components/Visualiser/VisualiserGraphBuilder.test.js

Fix shortest path feature in workbase
closes:  #138
1) Remove quotes around the ID in the shortest path query
2) Do not load other role-players that take part in the relation that are not part of the path

Shortest path bug

---

src/renderer/components/Visualiser/VisualiserUtils.js
test/unit/components/Visualiser/VisualiserUtils.test.js

To allow use to run multi-line queries with only the limit defined
closes #140
Improve get regex to match multiline queries before the get as well.

multi-line query with limit bug fix

---

.bazelrc
.circleci/config.yml
dependencies/graknlabs/dependencies.bzl

Recent upgrade of `bazel` version in `@graknlabs_build_tools` broke CI for `client-nodejs`. This PR aims to fix it by synchronizing `.bazelrc` with latest version in `build-tools`.
* Update `@graknlabs_build_tools` to the latest version
* Copy `.bazelrc` over from `@graknlabs_build_tools`
* Upgrade XCode image to match one used in graknlabs/grakn

Fix CI by synchronizing .bazelrc with @graknlabs_build_tools

---

.circleci/windows/assemble.py

`assemble-windows` CI job failed throwing `io.grpc.StatusRuntimeException: UNAVAILABLE: io exception` which did not allow Workbase tests to execute. Additionally, it was not possible to run the test on platforms other than Linux, which prevented developers from easily reproducing the issue locally.
Reason for test failing was that Grakn that was started at previous step (`[Remote]: starting Grakn`) was child of `bash` process that spawned it which resulted in terminating it when execution gets to `[Remote]: populating Grakn` step. As a solution, a similar approach to [one used in Grakn Core](https://github.com/graknlabs/grakn/blob/7f8c6dcfe0aa59c16f956151d5ec34fba06a17d5/test/assembly/windows/windows-zip.py#L176-L185) is implemented: Grakn Server is started and stopped as part of the same …

Various fixes to assemble-windows CI job

---

src/renderer/components/Visualiser/RightBar/ConceptInfoTab/RelationsPanel.vue

To fix the scroll bar showing in the relations panel in Workbase Windows
closes: #149
Modify overflow from scroll to auto

Relations panel scroll bug (WIndows)

---

src/renderer/components/shared/Preferences.vue

To disallow the user from clicking the test connection button when the state of the connection is valid or invalid
closes #110
Add disabled flag to element

Disable test connection button when connection state is valid or invalid

---

.circleci/config.yml

Fix deploy-github CI job by adding missing Bazel installation step

Fix deploy-github CI job by adding missing Bazel installation step

---

.circleci/config.yml

Fix bugs in deploy-github which causes the job to fail:
- Update the code for retrieving `ghr` binary
- Installed `certifi` which is required by the release notes automation

Fix bugs in deploy-github which causes the job to fail

---

.circleci/config.yml
BUILD.bazel
config/brew/BUILD
dependencies/graknlabs/BUILD
dependencies/graknlabs/dependencies.bzl

Bump 2018 in license headers to 2019
Bump `graknlabs` dependency on build tools to latest

Update License to 2019

---

src/renderer/components/Visualiser/VisualiserUtils.js
test/unit/components/Visualiser/VisualiserUtils.test.js

The users are now presented with an appropriate message when attempting to run a query that is currently not supported by Workbase.
closes: #174
Add additional checks to validate the query with respective tests
> originally implemented by Syed

Provides appropriate feedback when running unsupported queries

---

src/renderer/components/SchemaDesign/store/actions.js

Removing the association between a concept type and attribute type can be done regardless of whether or not the attribute type has any instances. This check has now been removed from the Schema Designer.
closes: #35 
Removes manual check for instances
> originally implemented by Syed

Removes check of instances when un-hasing an attribute from a concept type

---

src/renderer/components/CanvasVisualiser/Events.js
src/renderer/components/CanvasVisualiser/Visualiser.js
src/renderer/components/SchemaDesign/Style.js
src/renderer/components/Visualiser/Style.js
src/renderer/components/Visualiser/store/actions.js
src/renderer/components/shared/CanvasDataBuilder.js
test/unit/components/shared/CanvasDataBuilder.test.js

Makes the visualisation of the schema and concept type answers more informative by always showing labels and arrows on the edges.
- removes the unnecassary `.reduce(collect, [])` statements in `CanvasVisualiser/Events.js`
- adds `arrows`, `hiddenLabel` and `options` properties to edges in the `CanvasDataBuilder`
- extracts and moves parts of `showEdgeLabels` and `hideEdgeLabels` implementation to `showEdgeArrows` and `hideEdgeArrows`
- renames `showLabelsOnEdgesConnectedToNode` to `bringFocusToEdgesConnectedToNode` and add to it conditions that tailor its implementation based on the options on the edge options
- adds conditional behaviour to `onDragStart`, `onHoverNode` and `onDeselectNode` based on edge options
- removes edge property manipulation in `Visualiser/SchemaDesign > Style` and …

Shows labels and arrows on concept type answers and schema

---

src/renderer/components/Visualiser/VisualiserGraphBuilder.js
src/renderer/components/Visualiser/VisualiserUtils.js
src/renderer/components/shared/CanvasDataBuilder.js
test/unit/components/Visualiser/VisualiserGraphBuilder.test.js
test/unit/components/Visualiser/VisualiserUtils.test.js

Please replace every line in curly brackets ( { like this } ) with an appropriate description, and remove this line.
Fixes a bug with missing properties of the edge objects produced by double-clicking nodes. 
- modifies the functions in the `VisualiserUtils` and `VisualiserGraphBuilder` modules to use the `getEdge` function of `CanvasDataBuilder`
fixes #215

Fixes the bug with missing edge properties

---

src/renderer/components/CanvasVisualiser/Events.js

Fixes a bug where deselecting a node did not hide the label's according to the node's `options`. 
- in `Events > onDeselectNode` re-fetches the updated node after hiding labels and before hiding arrows.

Fixes a bug with hiding edges on deselecting nodes

---

src/renderer/components/Visualiser/store/actions.js
src/renderer/components/shared/CanvasDataBuilder.js

Fixes a bug with missing parameter passed to that led to error on explaining inferred instances.
- includes the missing parameter of `CDB> buildRPInstances` in `EXPLAIN_CONCEPT` visualiser action

Fixes a bug with explaining inferred concepts

---

.circleci/config.yml

We have added a validation step using `//ci:release-validate-deps` in order to ensure that biograkn is releasable only if it depends on a released version of Grakn Core

Use release-validate-deps to ensure that workbase depends on a released version of client-nodejs

---

src/renderer/components/shared/CanvasDataBuilder.js
src/renderer/components/shared/SharedUtils.js

Removes duplicate role edges in the Schema Designer.
- deduplicates the `edges` array produced within `CDB > buildTypes`

Fixes a bug with duplicate edges in Schema Designer

---

src/renderer/components/CanvasVisualiser/Facade.js
src/renderer/components/Visualiser/VisualiserUtils.js
src/renderer/components/Visualiser/store/actions.js
src/renderer/components/shared/CanvasDataBuilder.js
src/renderer/components/shared/SharedUtils.js
test/unit/components/Visualiser/VisualiserUtils.test.js
test/unit/components/shared/CanvasDataBuilder.test.js

Although attended to in a previous PR, duplicate edges were still present when explaining an inferred concept. With the current implementation, deduplication of edges and nodes takes place just before drawing them which we hope to be a more reliable approach.
- add (own) unique id in `edge` objects
- change same edge criteria to be the identical edge id values
- avoid adding duplicate edges and nodes in `Facade > addToCanvas`

Avoid duplicate edges

---

src/renderer/components/CanvasVisualiser/Facade.js
src/renderer/components/Visualiser/VisualiserUtils.js
src/renderer/components/Visualiser/store/actions.js
src/renderer/components/shared/CanvasDataBuilder.js
test/e2e/helpers/utils.js
test/helpers/mockedConcepts.js
test/unit/components/Visualiser/VisualiserUtils.test.js
test/unit/components/shared/CanvasDataBuilder.test.js

The nodes added to the visualiser as the result of double-clicking on node now contain all expected properties. In addition, the logic for producing the neighbour nodes has now moved to the Canvas Data Builder, which leads to better maintainability and testability. 
- moves functions related to loading neighbours to the `Canvas Data Builder`
- refactors the unit tests for loading neighbours to use the mocked concepts in the same way as they are used by the rest of the `CDB` unit tests
- improves the reliability of deduplication of nodes and edges in the `Facad`
- improves types, labels and/or values of mocked concepts 
**Note: ideally and eventually, we should only use the `mockedConcepts.js` (in place of `MockedConcepts.js` across all tests that require mocked concepts. This requires …

Fixes a bug with missing properties on nodes produced by double clicking

---

src/renderer/components/Visualiser/VisualiserUtils.js

Loading a relation's neighbours now works as expected regardless of the `Load Roleplayers` status in the settings.
- increments `limit`'s value by the node's `offset` in the query that retrieves neighbours of a relation instance.

Fixes the bug with loading relation neighbours when "load roleplayers" setting is on

---

src/renderer/components/shared/CanvasDataBuilder.js
test/unit/components/shared/CanvasDataBuilder.test.js

Previously, when constructing edges for a given node, all possible edges from that node were built regardless of whether the destination node was present in the visualiser. This is no longer the case and edges are only constructed between the given node and the nodes that are to be produced as a result of the given query.
- passes the list of existing node ids to `getTypeEdges` and `getInstanceEdges` and excludes edges where both their `to` and `from` nodes are not present within the list of given node ids.
resolves #199

Avoids building edges where its nodes are not visualised

---

src/renderer/components/Visualiser/store/actions.js

As a result of a recent bug, the dragging behaviour would break when the rendered nodes were added to the visualiser by shift + double-clicking on a node (loading attributes). This unexpected behaviour has been fixed.
- add missing properties to edges constructed as a result of shift + double-clicking on a node

Individual nodes are again draggable after shift + double-clicking on a node.

---

src/renderer/components/shared/CanvasDataBuilder.js

When the `Load Roleplayers` is switched on in the Settings, the visualised role edges no longer include the roles that are played by the roleplayer indirectly (via role hierarchies). Instead, the only role edge that is visualised belongs to the most granular role played by that roleplayer. 
- negates the roles that have a sub-role within the given relation

Visualises only the most granular role when loading roleplayers

---

RELEASE_TEMPLATE.md

Providing the correct installation instructions in the release template.
When running `brew tap-pin graknlabs/tap` your action is declined and you get this message 
> "Warning: Calling brew tap-pin user/tap is deprecated! Use fully-scoped user/tap/formula naming instead."
The release template was updated to a working solution.

Refer to Homebrew formula by full name

---

.circleci/config.yml
BUILD.bazel

Adapt `@graknlabs_workbase` to latest changes in bazel-distribution (in particular, graknlabs/bazel-distribution#150)
Instead of supplying `version_file` everywhere, use `--define version=<>` as a Bazel argument to supply version.

Refactor how version is provided to deployment rules

---

dependencies/graknlabs/dependencies.bzl

Currently CI is broken on `master` due to old transitive dependency.
Upgrade Grakn Core (such that Grakn Client Java is updated too) and `build-tools`

Fix CI by upgrading Grakn Core and build-tools

---

.gitignore
WORKSPACE
dependencies/graknlabs/dependencies.bzl
package.json
src/renderer/components/SchemaDesign/RightBar/ConceptInfoTab/AttributesPanel.vue
src/renderer/components/SchemaDesign/RightBar/ConceptInfoTab/PlaysPanel.vue
src/renderer/components/SchemaDesign/SchemaUtils.js
src/renderer/components/SchemaDesign/store/actions.js
src/renderer/components/Visualiser/RightBar/ConceptInfoTab/AttributesPanel.vue
src/renderer/components/Visualiser/VisualiserUtils.js
src/renderer/components/Visualiser/store/actions.js
src/renderer/components/shared/CanvasDataBuilder.js
static/styles/style.css
test/e2e/helpers/utils.js
test/helpers/mockedConcepts.js
test/unit/components/ScehmaDesign/SchemaUtils.test.js
test/unit/components/ScehmaDesign/store/actions.test.js
test/unit/components/Visualiser/VisualiserUtils.test.js
test/unit/components/Visualiser/store/actions.test.js
test/unit/components/shared/CanvasDataBuilder.test.js
yarn.lock

Changes introduced in this PR:
- make Workbase compatible with the latest release of `client-nodejs`
- fix a bug where attributes and roles were not displayed for the selected node in the Schema Designer 
- fix a bug in the scroll behaviour of the right sidebar in the Schema Designer
- make use of the newly introduced `asRemote()` when making Concept API calls
- remove the redundant async behaviour when reading local attributes of a concept
- refactor `mockedConcepts` to reflect the Concept API and make it easier to apply protocol changes moving forward
- remove `buildExplanationQuery` its helpers and associated unit tests as they are no longer used since the `explanation` protocol change
- fix post-processing of `attributes` and `roles` after loading the schema in the Schema Designer
- …

Makes Workbase compatible with the latest release of Client Node.js

---

electron-builder.yml
src/renderer/components/Visualiser/VisualiserUtils.js
src/renderer/components/Visualiser/store/actions.js
src/renderer/components/shared/CanvasDataBuilder.js
test/e2e/QuerySettings.test.js
test/unit/components/Visualiser/VisualiserUtils.test.js

Changes introduced in this PR are aimed at improving the performance of Workbase, by using the Concept API instead of constructing and running native Graql queries.
The post-processing step that occurs after visualising the graph for the user query, now uses the Concept API (instead of constructing and running a Graql query) to fetch the attributes of each node. Although this results in much faster retrieval of attributes, it does come with the limitation of missing inferred attributes. we will revert this change, once we have optimised the query planner for fast retrieval of attributes (of a given instance) through a Graql query.
When the user enables the _Load Roleplayers_ option and queries for a relation, without specifying its roleplayers, prior to this PR Workbase would run a Graql …

Improves performance of retrieving attributes and role players

---

dependencies/graknlabs/dependencies.bzl
package.json
src/renderer/components/SchemaDesign/LeftBar/NewAttributePanel.vue
src/renderer/components/SchemaDesign/RightBar/ConceptInfoTab/AttributesPanel.vue
src/renderer/components/SchemaDesign/SchemaHandler.js
src/renderer/components/SchemaDesign/SchemaUtils.js
src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlCodeMirror.js
src/renderer/components/Visualiser/VisualiserUtils.js
src/renderer/components/shared/CanvasDataBuilder.js
test/helpers/MockConcepts.js
test/helpers/gene.gql
test/helpers/mockedConcepts.js
test/integration/SchemaDesign/SchemaHandler.test.js
test/unit/components/ScehmaDesign/SchemaUtils.test.js
test/unit/components/Visualiser/VisualiserUtils.test.js
test/unit/components/shared/CanvasDataBuilder.test.js
yarn.lock

This PR brings the Grakn 1.8 support to Workbase.
resolves https://github.com/graknlabs/workbase/issues/290
Following https://github.com/graknlabs/client-nodejs/commit/b85668f7063b2313ed02ab35cd0922e67d1f9f4b
- `dataType` to `valueType`
- `datatype` to `value`
- `date` to `datetime`
- removing all references to `isImplicit`
- bump `client-nodejs` and `grakn-core` dependencies

Brings Grakn 1.8 Support

---

dependencies/graknlabs/dependencies.bzl
package.json
src/renderer/components/SchemaDesign/LeftBar/NewAttributePanel.vue
src/renderer/components/SchemaDesign/RightBar/ConceptInfoTab/AttributesPanel.vue
src/renderer/components/SchemaDesign/SchemaHandler.js
src/renderer/components/SchemaDesign/SchemaUtils.js
src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlCodeMirror.js
src/renderer/components/Visualiser/VisualiserUtils.js
src/renderer/components/shared/CanvasDataBuilder.js
test/helpers/MockConcepts.js
test/helpers/gene.gql
test/helpers/mockedConcepts.js
test/integration/SchemaDesign/SchemaHandler.test.js
test/unit/components/ScehmaDesign/SchemaUtils.test.js
test/unit/components/Visualiser/VisualiserUtils.test.js
test/unit/components/shared/CanvasDataBuilder.test.js
yarn.lock

Changes introduced in this PR, resolves the bug where multiline queries would sometimes lose their 1 to second last lines upon run, as illustrated in #249 
resolves https://github.com/graknlabs/workbase/issues/249
- fixed a regex pattern
- rearrange if statements for better readability

Ensures user's query is remained intact upon run

---

src/renderer/components/SchemaDesign/LeftBar/NewRulePanel.vue
src/renderer/components/SchemaDesign/store/actions.js
src/renderer/components/shared/CanvasDataBuilder.js

Changes introduced in this PR, ensure that 
- no error is displayed upon defining a new type
- defining a new type with role and attribute associations visualise nodes and edges as expected
- undefining a type succeeds as expected
- defining a rule succeeds as expected
resolves https://github.com/graknlabs/workbase/issues/280
resolves https://github.com/graknlabs/workbase/issues/294
resolves https://github.com/graknlabs/workbase/issues/272
the two methods of the CDB APIs (`getTypeNode` and `getTypeEdges`) are now sufficient for constructing nodes and edges in the Schema Designer.

Resolves various bugs in the Schema Designer

---

src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlEditor.vue

The user is now asked to select a keyspace, when they click on the GraqlEditor.
resolves https://github.com/graknlabs/workbase/issues/65

Notifies the user that no keyspace is selected, upon clicking on the GraqlEditor

---

src/renderer/components/Visualiser/TopBar/FavQueries/FavQueriesList.vue
src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlEditor.vue
static/styles/style.css

Multiline queries no longer lose their lines when being starred or applied as a starred query.
resolves https://github.com/graknlabs/workbase/issues/37

Retains lines of a multiline query when starring or applying a starred query

---

src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlEditor.vue
static/styles/style.css

The Graql Editor no longer contains blank lines which otherwise, would make the editor scrollable even with a single-line query.
resolves https://github.com/graknlabs/workbase/issues/307

Removes extra scrolling space from the Graql Editor

---

src/renderer/components/Visualiser/VisualiserUtils.js
test/unit/components/Visualiser/VisualiserUtils.test.js

Considering that Workbase, at the moment, only supports `match get` and `compute path` queries, when the user attempts to run an unsupported multiline query, they are presented with an informative error message. This change takes into account multiline queries in the query validation step.
resolves https://github.com/graknlabs/workbase/issues/265

Displays an error message when running a multiline unsupported query

---

src/renderer/components/Visualiser/VisualiserUtils.js
test/unit/components/Visualiser/VisualiserUtils.test.js

The change introduced in this PR, fixes the regex used in determining if the query should be extended with the `offset` and `limit` modifiers.

Fixes automatic extension of user's query with the `limit` and `offset` modifiers

---

src/renderer/components/Visualiser/store/actions.js

Explanation of an inferred concept that has previously been redrawn as part of a prior explanation now works as expected.
to retain the original explanation object attached to each node, we now avoid updating existing nodes upon explanation.
resolves https://github.com/graknlabs/workbase/issues/331

Excludes already-visualised nodes before updating canvas upon explanation

---

src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlCodeMirror.js

Single quoted strings in Graql queries are now highlighted correctly as strings.
resolves https://github.com/graknlabs/workbase/issues/326

Adds Graql syntax highlighting for single quoted strings

---

src/renderer/components/shared/CanvasDataBuilder.js
test/unit/components/shared/CanvasDataBuilder.test.js

When selecting attribute labels in the Display settings for a given type, the attribute label is added to the nodes' label even though the instance (i.e. node) does not own an instance of the selected attribute type. In this case, the attribute's value is displayed as empty. In addition, commas are no longer displayed at the end of each attribute label/value on the node's label. 
resolves https://github.com/graknlabs/workbase/issues/329
resolves https://github.com/graknlabs/workbase/issues/325

Improves presentation and logic of attributes displayed on a node's label

---

.circleci/config.yml
electron-builder.yml

It has been really painful for me to try and get the tar.gz build to work.
After some struggle I managed to get the app to launch but the screen would be blank.
Building .AppImage and executing that worked like a charm. It launched, there was no blank screen and the UI was usable.
Benefits of using AppImage: https://docs.appimage.org/introduction/advantages.html#advantages-for-users
Add AppImage as a target for Linux.

Add AppImage as a target for Linux

---

src/components/Login/LoginPage.vue

We fixed an issue where pressing ENTER caused the Visualiser window to disappear.
Fix ENTER key destroying visualiser window

Fix ENTER key destroying visualiser window

---

src/components/Login/LoginPage.vue

Fix enter key causing application turn into black screen in visualiser and schema designer.
- Remove enter key listener when leaving login page.
- Fix #372

Fix enter key causing application turn into black screen

---

src/components/SchemaDesign/store/actions.js

In 2.0 `deleteOwns` becomes stricter, which throws if type doesn't own the attribute. Do not delete attributes when the type to delete doesn't own the attribute.
- Fix https://github.com/graknlabs/workbase/issues/380

Do not delete attributes when type doesn't own the attribute

---

.grabl/automation.yml
BUILD.bazel
WORKSPACE

Validate that released Workbase depends on a proper version of TypeDB Client NodeJS
Add `//:release-validate-nodejs-deps` to validate `typedb-client` dependency

Validate NodeJS dependencies on release

---

.circleci/config.yml

As CircleCI is going to deprecate (and eventually delete) the old image we're using for building & testing on macOS, we need to upgrade it.
Bump version of XCode used for testing & building on macOS

Upgrade from deprecated version of XCode image

---

.circleci/config.yml

CircleCI jobs now clone the repository prior to executing the 'Bazel install script' (since the `.bazelversion` file must be present when the script is executed).
1. Make CircleCI jobs run the `checkout` step prior to `install-bazel-mac` or `install-bazel-linux`

Clone the repo prior to executing 'Bazel install' in CircleCI

---

view/common/KeyMapper.kt

We've set the "Replace" shortcut to `Ctrl+H` on Windows and Linux. Previously, it was `Ctrl+R` which is non-standard.
- Replace "Replace" shortcut to `Ctrl+H` on Windows and Linux

Replace "Replace" shortcut to `Ctrl+H` on Windows and Linux

---

view/common/geometry/Geometry.kt
view/graph/Vertex.kt

We bring the function for finding an attribute's edge endpoint in line with relation and entity's functions by allowing the offset to be nullable.
The user should see fewer crashes in the unlikely case that their schema causes the graph rendering logic to attempt to divide by zero.
We change the function signature of `ellipseIncomingLineIntersect` and `edgeEndpoint` to allow `Offset` to be nullable and detect this case in the body of `ellipseIncomingLineIntersect`.

Fix possible error when drawing an attribute's edge

---

.gitignore

We want it to be easier for developers to use other IDEs and OSes in the course of contributing to this repo without having to carefully manage what files get included in their PRs.
We have added more ignored files and folders to make it easier for developers to contribute to this repository, namely:
- VSCode
- Eclipse
- VIM
- TypeDB Studio
- Miscellaneous tooling files

Expand .gitignore to include IDE and OS-specific folders

---

Studio.kt
framework/common/WindowContext.kt
test/integration/Utils.kt

We fixed a bug in `WindowContext` where resizing the underlying window was not reflected when getting its values (i.e. height, width, x and y). This fixes a bug where certain actions such as mouse hovering didn't render tooltips because of windowContext reporting the incorrect height and width.
We've expanded WindowContext so that it includes 2 inner classes:
- Test, a 'mock' testing window context.
- Compose, a window context that links to the window itself when Studio is launched with a window.

Fix WindowContext not reflecting changes to window size

---

.grabl/automation.yml
dependencies/vaticle/repositories.bzl
test/integration/BUILD
test/integration/IntegrationTest.kt
test/integration/ProjectBrowserTest.kt
test/integration/QuickstartTest.kt
test/integration/TextEditorTest.kt
test/integration/TypeBrowserTest.kt
test/integration/Utils.kt

The Studio tests that required an instance of TypeDB have been migrated to using `typedb_kt_test`, which use `typedb-runner` to provide TypeDB to the tests rather than `typedb-extractor`. This migration has provided stability, increased hermeticity and the opportunity to test Studio's interactions with cluster in the future.
Studio tests that connect to TypeDB now use `typedb_kt_test`, a newly provided test rule from typedb-common that allow us to make use of TypeDB runners.
Utils is now an Object rather than a standalone set of functions and variables. It also provides a new test function `studioTestWithRunner`. Some Studio tests don't require the use of TypeDB and waiting for TypeDB to run is wasteful in those instances.
Studio tests are now stable in CI through an increase in delays to …

Migrate and stabilise Studio test suite

---

Studio.kt

We have fixed a bug where error windows were not provided window contexts and crashed before being able to show the error.
We provide a windowContext to the CompositionLocalProvider in the event of an error window being created.

Provide window context for error windows

---

state/connection/TransactionState.kt
test/integration/BUILD
test/integration/QueryRunnerTest.kt
test/integration/QuickstartTest.kt
test/integration/common/StudioActions.kt

When we run a query, we automatically include `TypeDBOptions` given the state of the toolbar. Currently, we derive the value of `explain` for `TypeDBOptions` from `infer`. We should derive it from `explain`.
We only turn on explanations when explain is on, not when `infer` is on.
We have also added a regression test to ensure that this issue does not return.

Toggling infer no longer toggles explanations

---

framework/common/KeyMapper.kt

The shortcut to open the replace dialog in Studio **on macOS** was `CTRL+R`, but it should be `CMD+R`. This has now been fixed.
This is a very small change 1+ 1- change, moving the line from under the CTRL modifier case to the CMD modifier case. Users should now be able to run `CMD+R` to open the replace functionality in Studio.

Fix replace shortcut for text editor

---

module/preference/PreferenceDialog.kt

We have improved the code providing the preferences dialog so that it is easier to understand and maintain in the future. The end user should experience no impact. Contributors and developers should have an easier time reading, understanding, maintaining and extending and interacting with the preferences dialog in the future.
We have 
- eliminated unnecessary uses of `val` in constructors where we don't intend to create a property for a class and only require the argument for instantiation. 
- converted `PreferenceField` into a class from an interface, since it provides implementation and data generic across its descendent classes. 
- moved functionality that is the same across descendent classes into the parent `PreferenceField` class.
- disambiguated the use of `Checkbox`, …

Improve preference dialog canonicalness

---

framework/material/Icon.kt

We've fix a bug we introduced a bug in:
- https://github.com/vaticle/typedb-studio/pull/629
where the size of icons was initialised as "Unspecified".  As a result, the icons became 'clipped', see: 
We believe the cause of this is that the function `.sp` doesn't have enough information in order to construct a `TextUnit` value at the time that the object is constructed. As such, it gives a `TextUnit` value of "Unspecified".
The only other place we use `.sp` in our application is in `//framework/common/theme/Typography.kt`, where we follow the pattern of declaring our sizes as `const` Ints and transforming them into `TextUnit` values later with `.sp`. We now follow this pattern in `//framework/material/Icon.kt` 
We've also made all the Icon enum class constructor arguments named.

Fix icon clipping

---

framework/common/KeyMapper.kt

We've changed the behaviour of the home key in the text editor, moving it to the beginning of the content covered by the text editor rather than the beginning of the line. This falls in line with our current implementation where SHIFT+HOME selects everything to the beginning of the content.
We've changed 
* `Keys.MoveHome` to map to `Command.MOVE_HOME` and
* `Keys.MoveEnd` to map to `Command.MOVE_END`.

Home/end keys move to beginning/end of content

---

framework/editor/EventHandler.kt
service/page/Pageable.kt
service/project/FileState.kt

We allow the running of a selected query from non-TypeQL files.
We no longer check whether a selection is from a TypeQL file before running it.
Closes https://github.com/vaticle/typedb-studio/issues/649

Allow running selected query from non-TypeQL files.

---

module/preference/PreferenceDialog.kt
service/common/DataService.kt
service/common/PreferenceService.kt
service/common/util/Label.kt
service/common/util/Sentence.kt
service/connection/QueryRunner.kt
service/connection/TransactionState.kt

We've added a field to the query runner preferences, allowing for the configuration of transaction timeouts.
Closes https://github.com/vaticle/typedb-studio/issues/642.
We've introduced:
* a preference field named `transactionTimeoutMins`, allowing the user to input a number of minutes between 1 and 10000 inclusive.
* the associated labels, captions, placeholders and additional assets to support the user in understanding the function of the preference field.
Additionally, we've refactored 
* `DataService` to provide the appropriate type rather than splitting half the conversions from strings to the appropriate between `PreferenceService` and `DataService`.
* ColumnSpacer, RowSpacer and other composables inherited from Form to not use redundant qualifiers. We used to have our own column …

Transaction Timeout Preference

---

framework/editor/TextRendering.kt
framework/graph/GraphArea.kt
framework/material/BUILD
framework/material/ContextMenu.kt
module/connection/BUILD
module/connection/DatabaseDialog.kt
module/project/ProjectBrowser.kt
module/type/BUILD
module/type/TypePage.kt
service/page/BUILD
service/page/PageService.kt
service/project/PathState.kt
service/schema/AttributeTypeState.kt
service/schema/EntityTypeState.kt
service/schema/RoleTypeState.kt
test/integration/common/BUILD
test/integration/common/StudioActions.kt

We've removed the ability to export schema from the database manager, as this isn't the appropriate place for the functionality (the database manager is solely for the management of databases). We plan to reintroduce this functionality into the menu bar when it is implemented.
We've also removed many unusued Kotlin loggers.
We've removed the export schema button from the database manager. 
We've removed unused Kotlin loggers.

Remove export schema button from database manager, unused kotlin loggers

---

.factory/automation.yml
framework/graph/GraphBuilder.kt
framework/output/RunOutputGroup.kt

Previously, Studio would visualise 'owns' edges that are inherited multiple times, even if the type from which it inherited this ownership is also present on the graph with its own 'owns' edge to the same attribute type.
Now, Studio only visualises owns, plays and sub edges for the 'super-est' edges that own, plays or are subtypes for those types that are visible on the graph.
We've introduced a new methodology for rendering schema vertices that waits until all the vertices are loaded onto the graph before completely resolve which edges it should draw. 
We've also removed functionality that supposedly ran upon the `GraphBuilder` completing, but actually run as soon as the graph building process had started.

Refactor schema vertex rendering for graph visualisation

---

module/type/TypeEditor.kt
service/schema/SchemaService.kt
service/schema/ThingTypeState.kt
service/schema/TypeState.kt

We no longer reload the entire schema and all its connections on each schema write. Instead, we now reload the type hierarchy (for the Type Browser), and also, while there is a Type Editor open, it reloads all its data on a schema write.
This change drastically reduces the time taken to complete schema write operations.
There was a bug (#723) where schema writes would freeze up Studio for a long time - specifically, it wouldn't be possible to commit the transaction or perform further queries. This was caused by overly aggressive refresh logic; we recursively loaded every edge for every type in the whole schema, using Studio's global schema write transaction. This rendered it unusable for anything until that refresh was done.
Now, we only reload the type hierarchy (necessary for Type …

Minimise queries made to refresh state after a schema write

---

.circleci/config.yml
.factory/automation.yml
BUILD
config/brew/typedb-studio.rb
dependencies/vaticle/artifacts.bzl
dependencies/vaticle/repositories.bzl
framework/graph/GraphBuilder.kt
framework/output/LogOutput.kt
test/integration/BUILD
test/integration/common/BUILD
test/integration/data/BUILD

We deploy 5 separate distributions of TypeDB Studio, one per platform:
1. `linux-x86_64`
2. `linux-arm64`
3. `mac-x86_64`
4. `mac-arm64`
5. `windows-x86_64`
Please be aware that this means TypeDB Studio distributions are no longer portable between Intel and Mac variants of the same system - eg. from an Intel mac to an ARM mac. 
* Add CPU architecture tags to assembly 
* Update homebrew formulae to handle arm and intel distribution

Deploy studio for each OS + Arch

---

.bazelrc
.circleci/config.yml
.circleci/windows/build.bat
.circleci/windows/prepare.bat
.circleci/windows/short_workspace.patch

We shorten bazel workspace path to work around the character limit on Windows, and enable runfiles linking for Rust compilation.

Windows build fixes

---

dependencies/vaticle/repositories.bzl

Due to a bug in the Java driver, we unpacked the driver dynamic library into the current working directory of Studio, rather than into a temporary directory. This was at best confusing, and at worst caused an unrecognized error in cases where the Studio was run from a read-only directory (such as `/Applications/` on mac OS.
We update to the driver version with the fix.

Fix unpacking driver runtime files into working directory

---

WORKSPACE
dependencies/vaticle/repositories.bzl
framework/material/Form.kt
module/connection/ServerDialog.kt
module/preference/PreferenceDialog.kt
service/common/util/Label.kt
service/common/util/Message.kt

We update typedb-driver with error UX improvements.
Drive-by: 
- fix connection dialog issue where if attempting to connect to TypeDB Enterprise with TLS disabled, but the root CA field (invisible to the user) having been populated, TLS would be forcibly enabled.
- disable the [Connect] button when attempting to connect to TypeDB Core Server with invalid address, and display a pop-up message

Update to driver with fixed error messages

---

service/connection/DriverState.kt

* We've updated the enterprise error prefix in places where we detect certain errors.
* Update 'CLS' to 'ENT'
We're aware that this is a hack, but currently these errors are not exposed in the API so it is not possible for us to detect certain errors cleanly.

Update Enterprise error code prefix

---

.circleci/config.yml
.circleci/windows/deploy.bat
.circleci/windows/deploy_release.bat
.circleci/windows/deploy_snapshot.bat
BUILD
RELEASE_TEMPLATE.md
WORKSPACE
config/brew/typedb-studio.rb
dependencies/vaticle/repositories.bzl
framework/editor/BUILD
framework/editor/common/BUILD
framework/editor/highlighter/common/BUILD
framework/editor/highlighter/typeql/BUILD
framework/graph/BUILD
framework/material/BUILD
framework/output/BUILD
module/preference/BUILD
module/project/BUILD
module/role/BUILD
module/rule/BUILD
module/type/BUILD
module/user/BUILD
service/common/BUILD
service/connection/BUILD
service/project/BUILD
service/schema/BUILD
test/integration/BUILD
test/integration/common/BUILD

We no longer upload build artifacts to the github releases page. Instead, the artifacts are available from our public cloudsmith repository, linked in the release notes.
- update ghr to 0.16.2, as 0.12.1 does not support github releases without artifacts

Deploy artifacts to CloudSmith

---

framework/editor/highlighter/typeql/typeql_scopes.yml

We fix the highlighting for string literals to make it yellow as it used to be. The highlighting had not been correct due to a bug introduced in TypeDB Studio 2.25.0. 
Before:
After:
The issue comes from [this PR](https://github.com/vaticle/typeql/commit/8bf4c1cd4a4609b4c45e21853f67db67ce73724b). 
We introduced `QUOTED_STRING` in the .g4 file as a new string literal, but we didn't fix the reference to the old `STRING_` in the studio. Now we did.

Fix syntax highlighting for quoted strings

---

.circleci/windows/dependencies.config
.circleci/windows/prepare.bat

Choco is `unable to resolve dependency 'python3 (= 3.7.4)'.` We upgrade to 3.9.

Update choco dependencies to use python39 package

---

framework/editor/InputTarget.kt

We store cursor positions when changing lines as described in https://github.com/vaticle/typedb-studio/issues/748. This is standard behaviour in other IDEs, such as IntelliJ IDEA and VSCode.
Before:
https://github.com/vaticle/typedb-studio/assets/51956016/9a4232b2-fb41-4276-9b48-76d741143329
After:
https://github.com/vaticle/typedb-studio/assets/51956016/0f311437-15f4-4a66-96d8-0005dedc6ad7
We store an additional piece of data in `Cursor`, `lastCol`. This remembers the last position of the column, which we only forget upon the creation of a new cursor by a method other than moving up or down a line.
Closes https://github.com/vaticle/typedb-studio/issues/748

Store cursor position when changing lines

---

module/connection/ServerDialog.kt
module/user/UpdateDefaultPasswordDialog.kt
service/common/DataService.kt
service/common/util/Label.kt
service/connection/DriverState.kt

We introduce a way to provide address translation when attempting to connect to cloud servers (cf. https://github.com/vaticle/typedb-driver/pull/624). This is useful when the route from the user to the servers differs from the route the servers are configured with (e.g. connection to public-facing servers from an internal network).
Note: we currently require that the user provides translation for the addresses of _all_ nodes in the Cloud deployment.

Cloud address translation

---

dependencies/maven/artifacts.snapshot
dependencies/vaticle/artifacts.bzl
dependencies/vaticle/repositories.bzl

We update `typedb` dependencies to run integration tests in the newly introduced `development-mode` that disables external reporting for CI and other test builds. We also fix `maven` artifacts after multiple `sync-dependencies` to fix the CI builds.

Update dependencies to typedb's development mode for integration tests and fix build

---

framework/common/KeyMapper.kt
framework/editor/EventHandler.kt

The behaviour of Home and End keys are now in line with most other text editors, moving to the start/end of the line (rather than the file) unless Ctrl (Cmd on MacOS) is additionally pressed.
We had some confusing terminology in the `Command` class - `MOVE_HOME` and `MOVE_END` intuitively sounded like they should correspond to a keyboard's Home and End keys, but this resulted in incorrect behaviour. We've renamed them to `MOVE_CONTENT_START` and `MOVE_CONTENT_END`, and these are now correctly only triggered by Ctrl+Home and Ctrl+End respectively. Home and End take you to the start/end of a line. If Shift is additionally pressed in any case, trigger selection.

In text editor, fix behaviour of Home and End keys

---

.circleci/config.yml

Migrates the  CircleCI mac jobs to arm64 executors
Migrates the  CircleCI mac jobs to arm64 executors, ahead of the shut-down of x86_64 executors on June 28th. In jobs for x86_64 builds of Mac, we update the steps to:
* Install rosetta
* Install bazelisk for the specific architecture, passed via a parameter ``<<bazel.arch>>`

Migrate CircleCI mac jobs to arm64 executors

---

.circleci/config.yml
BUILD

- TypeDB Driver `.dylib` and `.jnilib` files will now be deep signed to ensure correct notarisation
- We now perform code signing for Mac snapshots, to catch issues with it prior to release
- Expand the `mac_deep_sign_jars_regex`
- Add the required parameters when deploying mac snapshots

Deep sign TypeDB Driver and notarise Mac snapshots

---

.circleci/config.yml

Update the CircleCI image used for the Release Cleanup job
The existing image was invalid, and thus the job failed
We update the image to the same one we use for linux release

Update CircleCI image for Release Cleanup

---

module/connection/ServerDialog.kt
service/common/util/ConnectionUri.kt

We allow the use of URI schemes (for example, `https://` or `http://`) in connection addresses
Currently, our driver assumes `http://` if no scheme is supplied - sometimes, another scheme (such as `https://`) may be required. This is not possible through studio.
Two points are required to make this functional:
- Correct the `addressFormatIsValid` check to not view the `:` in a scheme as being a port delimiter. We achieve this through a regex with a negative lookahead, so that rather than splitting on `:` it splits on `:` not followed by `//`
- Rewrite the ConnectionURI parser to support schemes in addresses. We can no longer use the built-in `URI` class to parse it, as that fails when the addresses have a scheme. Similarly to address format checks, we make use of a regex with a negative …

Allow URI schemes in addresses

---

RELEASE_NOTES_LATEST.md
dependencies/typedb/repositories.bzl
framework/output/LogOutput.kt

Update the Driver dependency to work with optional concepts from rows
Replace a temporary `try {} catch` solution with an updated API's call. 
Check the optional result and get its concept instead of a temporary `try {} catch` block.

Update the Driver dependency to work with optional concepts from rows

---

dependencies/typedb/repositories.bzl
module/connection/ServerDialog.kt
service/connection/DriverState.kt

Update TypeDB driver dependency and use the unified driver constructor to support the latest API.
When Cloud mode is used, we just pick the first selected address and send the request (for address translation, it will probably fail the request with a connection error). It's the easiest thing we can do considering that the UI is not locked in 3.x even if the feature is not available.

Update TypeDB driver dependency and constructor

---

dependencies/maven/artifacts.snapshot

Update maven dependencies following the `typedb-dependencies` repo reference update.

Update maven dependencies

---

src/framework/graph-visualiser/graph.ts
src/framework/graph-visualiser/index.ts
src/framework/graph-visualiser/visualisation.ts
src/framework/typedb-driver/query-structure.ts

Add value type constraint to structure ( `match $x value string;` )
Needs typedb/typedb#7470

Add value type constraint to structure

---

src/framework/graph-visualiser/converter.ts
src/framework/graph-visualiser/visualisation.ts

We fixed a bug where schema vertex "islands" (with no edges) were not rendered in graph output.
It was confusing.
We add `put_kind` to the graph visualiser framework's `ILogicalGraphConverter` allowing it to handle query constraints tagged `kind`. When Studio's graph output in the Query pane sees a `kind` query constraint, we add a matching schema vertex to the graph for the schema type that it describes (if not already present).

Fix a bug where schema vertices with no edges were not rendered in graph output
