src/renderer/components/Login/LoginPage.vue
src/renderer/components/Visualiser/VisualiserUtils.js

closes #8
-Implements a connection panel to be shown to the user when Grakn is not running.
No
N/A

Workbase shows a blank screen when Grakn is not running

---

.bazelrc
.circleci/build-workbase-win/README.md
.circleci/build-workbase-win/build-workbase-win.py
.circleci/build-workbase-win/instance-setup-template.ps1
.circleci/config.yml
BUILD.bazel
WORKSPACE
package.json
test/e2e/QuerySettings.test.js
test/unit/components/store/actions.test.js

CI pipeline for Workbase

---

WORKSPACE

Needed for https://github.com/graknlabs/grabl/issues/14
Adds `grabl-marker` so dependency script knows how to update it

Add grabl-marker for automatically updating @graknlabs_grakn_core

---

src/renderer/components/Visualiser/VisualiserUtils.js
src/renderer/components/Visualiser/store/actions.js

Refactor double click queries to be compliant with Grakn 1.5
Move offset and limit after get

Update offset and limit of load neighbours and attribute queries

---

.circleci/config.yml
package.json

Fixes #71 
Fixes #75
- build DMG on Mac
- fix repo URL
- fix `appId`

Fixes in package.json: build DMG for mac, fix repo name

---

.circleci/build-workbase-win/build-workbase-win.py

Add windows cleanup after test

Add windows cleanup

---

src/renderer/components/Visualiser/VisualiserGraphBuilder.js

Filter concepts which were not requested in get clause
match $x isa person; $y isa company; get $x; => only $x should be returned
while also attaching the explanation to all the inferred concepts respectively.
- Refactor attachExplanation function.
- collect requested keys
- only return those concepts that were in the requested keys.

Filter concepts which were not requested in get clause

---

.circleci/config.yml
package.json

closes: #81
add the following to package.json:
"resolutions": {
"write-file-atomic": "2.4.1"
}

Fix flaky jest test

---

nohup.out

Remove unwanted nohup.out file from repo
delete nohup.out file

remove nohup.out file from repo

---

.circleci/config.yml

CI pipeline for releasing `workbase`
* Add `deploy_brew` for pushing Workbase to Caskroom
* Wire CircleCI jobs

Release pipeline for workbase

---

src/renderer/components/SchemaDesign/RightBar/ConceptInfoTab.vue
src/renderer/components/SchemaDesign/RightBar/ConceptInfoTab/PlaysPanel.vue
src/renderer/components/SchemaDesign/SchemaUtils.js
src/renderer/components/SchemaDesign/store/actions.js
src/renderer/components/shared/StoresActions.js
test/helpers/MockConcepts.js
test/unit/components/ScehmaDesign/SchemaUtils.test.js

closes: #113
closes: #116
To allow the user to add and remove the played roles from a schema concept
Implementation and UI for the Plays panel in the right bar of the schema designer

Plays panel in schema designer

---

src/renderer/components/SchemaDesign/SchemaUtils.js
test/helpers/MockConcepts.js

Filter implicit roles from plays panel
Modify test

Filter implicit roles from plays panel

---

src/renderer/components/Visualiser/store/actions.js

Fix bug for `shift+double click` on a node to retrieve attributes
Remove quotes around ID in the query for loading attributes

Fix retrieving of attributes of a node

---

.circleci/config.yml
.circleci/windows/assemble.py
package.json
src/renderer/components/Visualiser/TopBar.vue
src/renderer/components/Visualiser/TopBar/TypesContainer.vue
src/renderer/components/shared/Preferences.vue
src/renderer/customPlugins/notifications.js
test/e2e/ContextMenu.test.js
test/e2e/FavQueries.test.js
test/e2e/LoadNeighbours.test.js
test/e2e/QuerySettings.test.js
test/e2e/RelationsPanel.test.js
test/e2e/TypesPanel.test.js
test/e2e/VisualiserFooter.test.js
test/e2e/keyspaces.test.js
test/integration/SchemaDesign/SchemaHandler.test.js
test/integration/store/actions.test.js

To have end to end tests as part of the circle CI workflow
closes: #20 #21 #22
Upgrade Spectron to 5.0.0
Refactor e2e tests
Enable e2e tests in ci config

Enable e2e tests

---

.circleci/windows/assemble.py

To disable e2e test on windows for the time being
Will be handled in the next milestone under issue #22
N/A

Disable e2e test on windows

---

.circleci/config.yml

Update machine type for the deploy-github job

Update machine type for the deploy-github job

---

src/renderer/components/Visualiser/RightBar/SettingsTab/DisplaySettingsPanel.vue

Modified Label to Attribute Label in the display panel to be more consistent with functionality 
close: #36 
subtitle modification

Modify display settings Label to Attribute Label

---

README.md

The readme now contains instructions on:
- building from source,
- running in development mode, and
- running tests

Includes build, develop and test instructions in the readme

---

.circleci/config.yml
test/e2e/LoadNeighbours.test.js
test/e2e/QuerySettings.test.js

In a previous PR, two tests that were failing because of a Grakn bug were commented out. Since the aforementioned bug [has been fixed](https://github.com/graknlabs/grakn/pull/5394), these tests are now uncommented.

Re-includes the tests that relate to loading relation neighbours

---

.github/CODEOWNERS

We've added Soroush as the code owner since he is the biggest contributor.

Add Soroush as the code owner

---

dependencies/graknlabs/dependencies.bzl
package.json
yarn.lock

Release Grakn Workbase 1.2.4
- uses the latest build-tools

Release 1.2.4

---

.circleci/config.yml

Fix CI issues caused by outdated configuration
Upgrade Windows Orb to 2.0.0

Upgrade CircleCI Orb to version that contains needed tools

---

src/renderer/components/SchemaDesign/RightBar.vue
src/renderer/components/Visualiser/RightBar.vue

The right-bar in the Visualiser and Schema Designer now becomes scrollable as its height exceeds the maximum height of the main window.
- styles the right-bar with the correct `max-height` and `overflow` values.

Makes the right-bar scrollable

---

src/renderer/store/actions.js

A bug in the previous release of Workbase, caused authentication to Grakn KGMS to always fail. This bug has now been fixed and Grakn Workbase can securely connect to an instance of Grakn KGMS

Fixes authenticating access to Grakn KGMS

---

.circleci/config.yml
.circleci/windows/dependencies.config
.circleci/windows/prepare.bat

We have fixed the issue that causes `assemble-windows-zip` to fail

Fix Workbase's CI (assemble-windows-zip is failing)

---

src/renderer/components/Visualiser/store/actions.js

Given that all inferred concepts retrieved within a single answer share the same explanation object, we now ensure that when explaining a concept, only the concepts that are a part of the specific explanation of the given concept are visualised, as opposed to concepts that explain the other inferred concepts of the same explanation object. 
When retrieving the rule explanations of answers (of a join explanation), we now filter out the answers that are unrelated to the node that's being explained.

Explains only the given inferred concept

---

.bazelignore
BUILD.bazel
vue.config.js

Include OS and version in the name of released Workbase artifacts.
Produce artifacts with the OS and version included in the name; use a wildcard in zip targets to match it.

Include OS and version in the release asset name

---

src/components/MainTemplate/MainTemplate.vue
src/components/SchemaDesign/RightBar.vue

Make application main window non-scrollable.
- fix #373

Fix the application main window being scrollable

---

BUILD.bazel

Deploy Workbase to Homebrew
Add a checksum target that was missing

Fix Homebrew deployment

---

src/store/actions.js

Fix database loading and creation deletion using cluster.
- `await` for cluster client result.
- fix https://github.com/graknlabs/workbase/issues/375

Fix cluster database loading

---

src/components/SchemaDesign/TopBar.vue
src/main.js
src/store/actions.js

Close schema session and transactions after switching to visualiser.
- Close schema session and transactions after switching to visualiser.
- Fix https://github.com/graknlabs/workbase/issues/382

Close schema session after switching to visualiser

---

.grabl/automation.yml

Improve `deploy-brew` job to not do extraneous things.
Remove downloading and computing checksum of the released archive

Cleanup Brew deployment job

---

dependencies/graknlabs/repositories.bzl

Allow Homebrew deployment of Workbase
Bump `@graknlabs_dependencies` to latest `master`

Upgrade @graknlabs_dependencies

---

.circleci/config.yml
.grabl/automation.yml

Allow deployment to Homebrew
Fix #390
Deploy to Homebrew from he same job as the one generating a Mac artifact

Fix deployment to Homebrew

---

package.json

Bump grakn-client to 2.0.1
Bump grakn-client to 2.0.1

Bump grakn-client to 2.0.1

---

package-lock.json
package.json
src/components/Login/LoginPage.vue
src/components/SchemaDesign/store/actions.js
src/components/ServerSettings.js
src/components/Visualiser/TopBar/TypeQLEditor/TypeQLEditor.vue
src/components/Visualiser/store/actions.js
src/components/shared/SharedUtils.js
src/main.js
src/store/actions.js

Provide authentication and encryption connection to cluster.
- Provide authentication and encryption connection to cluster.

Provide authentication and encryption connection to cluster

---

src/components/Login/LoginPage.vue
src/store/actions.js

Update password mask & root CA optionality.
Update password mask & root CA optionality.

Update password mask & root CA optionality

---

.circleci/config.yml
BUILD

We've updated `@vaticle_dependencies`, bringing in the new release notes creation script.
1. Update `@vaticle_dependencies` version
2. Add the new release notes creation script to the CircleCI job

Add release notes script

---

dependencies/vaticle/artifacts.bzl
dependencies/vaticle/repositories.bzl
service/common/util/Message.kt
service/connection/ClientState.kt

We've added a password expiry notification advising users to use Console to update their password once it is within 7 days of expiring.
We've added a warning when the user's password is nearly expired. We specify how many days until the password will expire if left untouched.

Password expiry notification

---

dependencies/vaticle/repositories.bzl

We've bumped dependencies to fix an error we encountered during release, where the notes tool errors when it encounters a PR without a body.
We've bumped dependencies to fix an error we encountered during release, where the notes tool errors when it encounters a PR without a body.

Bump dependencies

---

.factory/automation.yml
framework/graph/GraphBuilder.kt

We've refactored the graph building process to derive 'has' edges from the remote concept API.
We've refactored functionality to build has edges from the remote concept of a thing.

Use remote concept API to derive has edges for graph visualisation

---

framework/graph/GraphBuilder.kt
framework/output/LogOutput.kt

We now handle the possibility of Values being returned as part of a ConceptMap. Retrieved pure values are not displayed in the graph view, but printed out as expected in the log view.
Closes #791

Support value variables in log output

---

WORKSPACE
dependencies/maven/artifacts.snapshot
dependencies/vaticle/artifacts.bzl
dependencies/vaticle/repositories.bzl
framework/graph/GraphBuilder.kt
framework/output/LogOutput.kt
framework/output/RunOutputGroup.kt
module/preference/PreferenceDialog.kt
service/common/DataService.kt
service/common/PreferenceService.kt
service/connection/QueryRunner.kt
service/schema/AttributeTypeState.kt
service/schema/BUILD
service/schema/EntityTypeState.kt
service/schema/RelationTypeState.kt
service/schema/RoleTypeState.kt
service/schema/SchemaService.kt
service/schema/ThingTypeState.kt
service/schema/TypeState.kt
test/integration/TextEditorTest.kt
test/integration/common/StudioActions.kt
test/integration/data/sample_github_data/github_collaborators_query.tql

We update to the newest version of TypeDB Driver which supports Fetch queries. As Fetch queries return a stream of JSONs, they are only available in text output view, not as a graph.
For more details, see https://github.com/vaticle/typeql/pull/300
Closes https://github.com/vaticle/typedb/issues/6921

Implement Fetch query

---

service/common/util/ConnectionUri.kt

- Add the license header to `ConnectionUri.kt`

Fix checkstyle for ConnectionUri.kt

---

service/common/util/ConnectionUri.kt

We fix an issue where attempting to parse `typedb-core://` connection URIs would cause crashes
This issue made this feature unusable for TypeDB Core connection URIs
We separate the logic for parsing addresses for TypeDB Cloud - which expects a username and password - from the address parsing logic for TypeDB Core - which doesn't. Instead of attempting to extract data it doesn't need from the `authority` component of the URI, which resulted in an empty list of addresses, we simply take the entire `authority` component as the address.

Separate address parsing logic for Core and Cloud connection URIs

---

src/service/query-tool-state.service.ts

Table renderer collects lines in a string of array before updating the DOM
Results with a large number of rows were slow to render
Table renderer collects lines in a string of array before updating the DOM

Table renderer collects lines in an array of strings before updating the DOM

---

src/service/query-tool-state.service.ts

Fix bug where the log output was not being updated in case of errors.
We were pushing to lines, but returning immediately afterwards.

Fix bug where the log output was not being updated in case of errors.
